openapi: 3.0.3
info:
  title: "1С:Микрофинансовая организация"
  description: |-
    Сервис микрокредитования
  version: kz
servers:
  - url: https://unknown.kz

paths:
  /ping:
    get:
      tags:
        - Ping
      summary: Тестирование связи
      description: Подробное описание
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
        
  /leads:
    post:
      tags:
        - Заявки на кредит
      summary: Сервис для работы с заявками на микрокредит
      description: Создает ФизЛицо, Контрагента, Залог и Заявку
      requestBody:
        required: true
        description: Описание для JSON
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loan'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponseAPI'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseAPI'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Optional, but helps document expected token type
  schemas:
    Loan:
      type: object
      properties:
        date:
          description: "Дата заявки на получение микрокредита"
          type: string
          format: date-time
          example: "2025-01-22T20:50:43"
        creditPipelineNumber:
          type: string
          minLength: 10
          maxLength: 10
          example: "12345"
          description: "Номер заявки в КК"
        borrower:
          $ref: '#/components/schemas/Contragent'
        managerIIN:
          description: "ИИН кредитного менеджера"
          type: string
          example: "951109400079"
          minLength: 13
          maxLength: 13
        creditProductId:
          description: "Идентификатор кредитного продукта (код элемента из 1С:МФО)"
          type: string
          example: "000000001"
          minLength: 10
          maxLength: 10
        amount:
          type: number
          format: double
          description: 'Сумма заема'
          example: "3 000 000.00"
        currencyId:
          description: 'Код валюты по справочнику 1С:МФО'
          type: string
          example: "398"
          minLength: 3
          maxLength: 3
        loanTerm:
          description: 'Срок заема'
          type: integer
          example: "60"
        loanPurposeId:
          description: "Идентификатор цели кредитования (код элемента из 1С:МФО)"
          type: string
          example: "000000001"
          minLength: 10
          maxLength: 10
        clientConsentId:
          description: |
            Согласие клиента (поле заявки на микрокредит).<br>
            0 - Не задано<br>
            1 - Согласие<br>
            2 - Отказ<br>
          type: integer
          example: "60"
        car:
          $ref: '#/components/schemas/Car'
        guarantor:
          $ref: '#/components/schemas/Contragent'
        status:
          type: string
          description: "Статус"
        
    Car:
      type: object
      required:
        - vin
        - markaId
        - modelId
        - variantId
        - year
        - mileage
      properties:
        vin:
          type: string
          example: "Z8NFBAJ11ES089400"
          description: "VIN"
        markaId:
          type: integer
          example: 97
          description: "Идентификатор марки"
        modelId:
          type: integer
          example: 1030
          description: "Идентификатор модели"
        variantId:
          type: integer
          example: 14199
          description: "код варианта"
        year:
          type: integer
          example: 2019
          description: "Год выпуска"
        bodyTypeId:
          type: string
          example: "6"
          description: "Тип кузова"
        dwheelType:
          type: string
          example: "Передний"
          description: "Тип привода"
        transmissionId:
          type: string
          example: "1"
          description: "Код трансмиссии"
        engineVolume:
          type: string
          example: "1997"
          description: "Объем двигателя"
        engineTypeId:
          type: string
          example: "1"
          description: "Идентификатор типа двигателя"
        color:
          type: string
          example: "Белый"
          description: "Наименование цвета"
        mileage:
          type: integer
          example: 58371
          description: "Пробег"
        interiorMaterials:
          type: string
          example: "Темный"
          description: "Материалы салона"
        steering:
          type: string
          example: "1"
          description: "Расположение руля"
        engineNumber:
          type: string
          example: "?"
          description: "Номер двигателя"
    
    Address:
      type: object
      properties:
        postAddress:
          type: string
          example: "г.Алматы Медеуский район Хоружей 75"

    ContragentDocument:
      type: object
      description: |
          Документ идентификации личности
          (удостоверение, паспорт и т. д.)
      required:
        - number
        - issuedAuthority
        - documentType
        - series
        - dateOfIssue
        - dateOfExpiration
      properties:
        documentType:
          type: string
          example: "Удостоверение личности РК"
          minLength: 1
          maxLength: 100
          description: "Тип документа"
        series:
          type: string
          example: ""
          minLength: 0
          maxLength: 100
          description: "Серия документа"
        number:
          type: string
          example: "042555774"
          minLength: 1
          maxLength: 30
          description: "Номер документа"
        dateOfIssue:
          type: string
          format: date
          example: "2017-04-07"
          description: "Дата выпуска документа"
        dateOfExpiration:
          type: string
          format: date
          example: "2017-04-07"
          description: "Дата истечения срока действия документа"
        issuedAuthority:
          type: string
          example: "МВД РК"
          description: "Ведомство выдавшее документ"

    Contragent:
      type: object
      required:
        - iin
        - birthdate
        - address
        - clientLanguage
        - gender
        - document
        - firstName
        - lastName
        - middleName
        - phone
        - isBusiness
        - countryCode
        - email
      properties:
        document:
          $ref: '#/components/schemas/ContragentDocument'
        iin:
          type: string
          example: '830622301914'
          description: "ИИН"
        birthdate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата рождения"
        address:
          type: string
          example: 'Алматинская область Енбекшиказахский район Рахатский с.о. Арычная 7А'
          description: "Адрес"
        clientLanguage:
          type: string
          example: 'RU'
          description: "Язык"
        gender:
          type: string
          example: 'M'
          description: "Пол"
        firstName:
          type: string
          example: 'Дәурен'
          description: "Имя"
        lastName:
          type: string
          example: 'Айтбаев'
          description: "Фамилия"
        middleName:
          type: string
          example: 'Қанатұлы'
          description: "Отчество"
        phone:
          type: string
          example: '77009752107'
          description: "Номер телефона"
        countryCode:
          type: string
          example: 'KAZ'
          description: "Код страны"
        email:
          type: string
          example: null
          description: "Адрес электронной почты"
        registrationCountry:
          type: string
          example: 'Казахстан'
          description: "Наименование страны регистрации"
        isBusiness:
          type: boolean
          example: false
          description: "Это юридическое лицо?"

    SuccessResponseAPI:
      type: object
      properties:
        result:
          type: string
          example: "ok"
          description: "Краткое и емкое описание результата выполнения запроса"
        loanAgreementNumer:
          type: string
          example: "????"
          description: "Номер договора кредита"
        loanAgreementDate:
          type: string
          example: "????"
          description: "Дата договора кредита"
        pledgeAgreementNumer:
          type: string
          example: "????"
          description: "Номер договора залога"
        pledgeAgreementDate:
          type: string
          example: "????"
          description: "Дата договора залога"
        insuranceContractNumber:
          type: string
          example: "????"
          description: "Номер договора КАСКО"
        insuranceContractDate:
          type: string
          example: "????"
          description: "Дата договора КАСКО"
        data:
          type: string
          example: ""
  
    ErrorResponseAPI:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Неверный формат данных: (Описание ошибки)"
        data:
          type: string
          example: ""
  
    