openapi: 3.0.3
info:
  title: "1С:Микрофинансовая организация"
  description: |-
    Сервис микрокредитования
  version: kz
servers:
  - url: http://914f098f0c18.sn.mynetname.net:8081/1c_mfo/hs/

paths:
  /leads/ping:
    get:
      tags:
        - Тестирование соединения
      summary: Тестирование связи
      description: Подробное описание
      responses:
        '200':
          description: Successful operation
        
  /leads:
    post:
      tags:
        - Заявки на кредит
      summary: Сервис для работы с заявками на микрокредит
      description: Создает ФизЛицо, Контрагента, Залог и Заявку
      requestBody:
        required: true
        description: Описание для JSON
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loan'
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponseAPI'
        '400':
          description: "Текстовая ошибка"
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Ошибка чтения сущности "ЗаявкаНаКредит"
                  	Ошибка чтения поля "borrower"
                  		Ошибка чтения сущности "Клиент"
                  			Ошибка чтения поля "iin"
                  				Ошибки в значении ИИН 891211555666
                  					Контрольное число для ИИН не совпадает с рассчитанным.

# Глобальное применение схемы безопасности ко всем путям
security:
  - basicAuth: []
  
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Loan:
      type: object
      properties:
        date:
          description: "Дата заявки на получение микрокредита"
          type: string
          format: date-time
          example: "2025-01-22T20:50:43"
        creditPipelineNumber:
          type: string
          minLength: 10
          maxLength: 10
          example: "12345"
          description: "Номер заявки в КК"
        borrower:
          $ref: '#/components/schemas/Contragent'
        managerIIN:
          description: "ИИН кредитного менеджера"
          type: string
          example: "951109400079"
          minLength: 12
          maxLength: 12
        creditProductId:
          description: "Идентификатор кредитного продукта (код элемента из 1С:МФО)"
          type: string
          example: "000000001"
          minLength: 10
          maxLength: 10
        amount:
          type: number
          format: double
          description: 'Сумма заема'
          example: "3 000 000.00"
        currencyId:
          description: 'Код валюты по справочнику 1С:МФО'
          type: string
          example: "398"
          minLength: 3
          maxLength: 3
        loanTerm:
          description: 'Срок заема'
          type: integer
          example: "60"
        loanPurposeId:
          description: "Идентификатор цели кредитования (код элемента из 1С:МФО)"
          type: string
          example: "000000001"
          minLength: 10
          maxLength: 10
        car:
          $ref: '#/components/schemas/Car'
        loanСollateralCost:
          type: number
          format: double
          description: 'Сумма обеспечения кредита'
          example: "3 000 000.00"
        downPayment:
          type: number
          format: double
          description: 'Сумма первоначального взноса (если не заполнен процент в downPaymentPercentage)'
          example: "1 000 000.00"
        downPaymentPercentage:
          type: number
          format: double
          description: 'Процент первоначального взноса (если не заполнена сумма в downPayment)'
          example: "10.0%"
        status:
          type: string
          description: |
            1) loan - Заявление
            2) cancel - Отказ от займа
            3) contract - Кредитное соглашение
            4) completed - Выдача займа
          example: "loan"
          minLength: 1
          maxLength: 40
        guaranteeObligation:
          $ref: '#/components/schemas/GuaranteeObligation'
        
    GuaranteeObligation:
      type: object
      properties:
        guarantor:
          $ref: '#/components/schemas/Contragent'
        acceptedGuaranteeAmount:
          type: number
          format: double
          description: 'Сумма принятой гарантии'
          example: "5 000 000.00"
        warrantyPeriod:
          description: "Срок действия гарантии"
          type: string
          format: date-time
          example: "2025-01-22T20:50:43"
    Car:
      type: object
      required:
        - vin
        - marka
        - model
        - variant
        - year
        - mileage
      properties:
        vin:
          type: string
          example: "Z8NFBAJ11ES089400"
          description: "VIN"
        marka:
          type: string
          example: "Lada"
          description: "Марка"
        model:
          type: string
          example: "Priora"
          description: "Мдель"
        variant:
          type: string
          example: "Вариант"
          description: "Вариант"
        year:
          type: integer
          example: 2019
          description: "Год выпуска"
        bodyType:
          type: string
          example: "6"
          description: "Тип кузова"
        dwheelType:
          type: string
          example: "Передний"
          description: "Тип привода"
        transmission:
          type: string
          example: "1"
          description: "Трансмиссия"
        engineVolume:
          type: string
          example: "1997"
          description: "Объем двигателя"
        engineType:
          type: string
          example: "1"
          description: "Тип двигателя"
        color:
          type: string
          example: "Белый"
          description: "Наименование цвета"
        mileage:
          type: integer
          example: 58371
          description: "Пробег"
        interiorMaterials:
          type: string
          example: "Темный"
          description: "Материалы салона"
        steering:
          type: string
          example: "1"
          description: "Расположение руля"
        engineNumber:
          type: string
          example: "123456"
          description: "Номер двигателя"
    
    ContragentDocument:
      type: object
      description: |
          Документ идентификации личности
          (удостоверение, паспорт и т. д.)
      required:
        - number
        - issuedAuthority
        - documentType
        - series
        - dateOfIssue
        - dateOfExpiration
      properties:
        documentType:
          type: string
          example: "Удостоверение личности РК"
          minLength: 1
          maxLength: 100
          description: "Тип документа"
        series:
          type: string
          example: ""
          minLength: 0
          maxLength: 100
          description: "Серия документа"
        number:
          type: string
          example: "042555774"
          minLength: 1
          maxLength: 30
          description: "Номер документа"
        dateOfIssue:
          type: string
          format: date
          example: "2017-04-07"
          description: "Дата выпуска документа"
        dateOfExpiration:
          type: string
          format: date
          example: "2017-04-07"
          description: "Дата истечения срока действия документа"
        issuedAuthority:
          type: string
          example: "МВД РК"
          description: "Ведомство выдавшее документ"

    Contragent:
      type: object
      required:
        - iin
        - birthdate
        - birthPlace
        - address
        - clientLanguage
        - gender
        - document
        - firstName
        - lastName
        - middleName
        - phone
        - registrationCountry
        - countryCode
        - email
      properties:
        document:
          $ref: '#/components/schemas/ContragentDocument'
        iin:
          type: string
          example: '830622301914'
          description: "ИИН"
          minLength: 12
          maxLength: 12
        birthdate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата рождения"
        birthPlace:
          type: string
          example: 'РК'
          description: "Место рождения"
        address:
          type: string
          example: 'Алматинская область Енбекшиказахский район Рахатский с.о. Арычная 7А'
          description: "Адрес"
        clientLanguage:
          type: string
          example: 'RU'
          description: "Язык"
        gender:
          type: string
          example: 'M'
          description: "Пол"
        firstName:
          type: string
          example: 'Дәурен'
          description: "Имя"
        lastName:
          type: string
          example: 'Айтбаев'
          description: "Фамилия"
        middleName:
          type: string
          example: 'Қанатұлы'
          description: "Отчество"
        phone:
          type: string
          example: '77009752107'
          description: "Номер телефона"
        countryCode:
          type: string
          example: 'KAZ'
          description: "Код страны"
        email:
          type: string
          example: null
          description: "Адрес электронной почты"
        registrationCountry:
          type: string
          example: 'Казахстан'
          description: "Наименование страны регистрации"

    SuccessResponseAPI:
      type: object
      properties:
        loanApplicationNumber:
          type: string
          example: "1-000000020"
          description: "Номер заявления на получение кредита"
        loanApplicationDate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата заявления на получение кредита"
        loanAgreementNumer:
          type: string
          example: "1-000000020"
          description: "Номер договора кредита"
        loanAgreementDate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата договора кредита"
        pledgeAgreementNumer:
          type: string
          example: "1-000000020"
          description: "Номер договора залога"
        pledgeAgreementDate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата договора залога"
        insuranceContractNumber:
          type: string
          example: "1-000000020"
          description: "Номер договора КАСКО"
        insuranceContractDate:
          type: string
          format: date
          example: '1983-06-22'
          description: "Дата договора КАСКО"
    